# Generated by Django 3.2.7 on 2021-11-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='age',
        ),
        migrations.AddField(
            model_name='myuser',
            name='dob',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='sex',
            field=models.CharField(max_length=250),
        ),
    ]
