# Generated by Django 3.2.7 on 2021-11-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0005_auto_20211119_0305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
